import json
import os
from dotenv import load_dotenv  # <--- Import this
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate

# 1. Load the environment variables from .env
load_dotenv() 

# 2. Fetch the key securely
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise ValueError("❌ API Key missing! Add GOOGLE_API_KEY to your .env file.")

def load_source_schema():
    # Points to the schema file generated by connector/schema_discovery.py
    schema_path = "../connector/hospital_schema.json"
    if not os.path.exists(schema_path):
        print(f"❌ Error: {schema_path} not found. Run schema_discovery.py first.")
        return None
    with open(schema_path, "r") as f:
        return json.load(f)

FHIR_TARGET_STRUCTURE = """
Target FHIR Resources needed:
1. Patient: needs id, name[0].given, name[0].family, birthDate, gender, telecom
2. Encounter: needs id, subject.reference, class, period.start, status
3. Observation: needs id, code.text, valueQuantity, effectiveDateTime
"""

def generate_auto_mapping():
    source_schema = load_source_schema()
    if not source_schema: return

    llm = ChatGoogleGenerativeAI(
        model="gemini-pro",
        google_api_key=GOOGLE_API_KEY,
        temperature=0
    )

    prompt = PromptTemplate(
        input_variables=["source_schema", "target_hints"],
        template="""
        Act as a FHIR Data Engineer. Map this Hospital SQL Schema to FHIR R4.
        
        SOURCE SCHEMA: {source_schema}
        TARGET REQUIREMENTS: {target_hints}
        
        OUTPUT JSON ONLY (No markdown):
        {{
          "patient": {{
            "source_table": "table_name",
            "target_resource": "Patient",
            "field_mappings": [
              {{ "source_field": "col_name", "target_path": "fhir_path", "transformation": "func_name_if_needed" }}
            ]
          }}
        }}
        """
    )

    print("🤖 AI is mapping your schema...")
    chain = prompt | llm
    response = chain.invoke({
        "source_schema": json.dumps(source_schema),
        "target_hints": FHIR_TARGET_STRUCTURE
    })

    content = response.content.replace("```json", "").replace("```", "")
    
    with open("fhir_mappings.json", "w") as f:
        f.write(content)
    print("✅ Mapping saved to fhir_mappings.json")

if __name__ == "__main__":
    generate_auto_mapping()